# Generated by Django 6.0.2 on 2026-03-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0006_rename_answer_clue_normalized_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='Description', max_length=200),
            preserve_default=False,
        ),
    ]
