# Generated by Django 6.0.2 on 2026-03-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0007_board_description'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER INDEX IF EXISTS crossword_cluecelle8f009_idx
                RENAME TO crossword_row_ind_e8f009_idx;
            """,
            reverse_sql="""
                ALTER INDEX IF EXISTS crossword_row_ind_e8f009_idx
                RENAME TO crossword_cluecelle8f009_idx;
            """,
        ),
    ]
