# Generated by Django 6.0.2 on 2026-03-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0008_rename_crossword_cluecelle8f009_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cluecell',
            new_name='crossword_c_row_ind_01463c_idx',
            old_name='crossword_row_ind_e8f009_idx',
        ),
    ]
