# Generated by Django 6.0.2 on 2026-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0011_alter_cluecell_options_cluecell_placement_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': (['puzzle_number'],)},
        ),
        migrations.AddField(
            model_name='board',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='puzzle_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
