# Generated by Django 6.0.2 on 2026-03-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0014_board_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='published',
        ),
    ]
