# Generated by Django 6.0.2 on 2026-03-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0015_remove_board_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
