# Generated by Django 6.0.2 on 2026-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0016_rename_published_date_board_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
