# Generated by Django 6.0.2 on 2026-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0017_board_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='puzzle_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
