# Generated by Django 6.0.2 on 2026-03-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0020_alter_board_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
