# Generated by Django 6.0.2 on 2026-04-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0023_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boards', models.ManyToManyField(blank=True, related_name='design_notes', to='crossword.board')),
                ('categories', models.ManyToManyField(blank=True, related_name='design_notes', to='crossword.designcategory')),
            ],
            options={
                'ordering': ['design_number'],
            },
        ),
    ]
