# Generated by Django 6.0.2 on 2026-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0024_designcategory_designnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
