# Generated by Django 6.0.2 on 2026-06-14 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0026_clue_anagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('col_index', models.PositiveIntegerField()),
                ('placement_index', models.PositiveIntegerField()),
                ('letter', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['placement_index'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_row', models.PositiveIntegerField()),
                ('start_col', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('A', 'Across'), ('D', 'Down')], max_length=1)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='cluecell',
            name='cluecell_row_col_idx',
        ),
        migrations.RemoveConstraint(
            model_name='cluecell',
            name='clue_cell_unique_placement_row_col',
        ),
        migrations.RemoveConstraint(
            model_name='cluecell',
            name='clue_cell_unique_placement_placement_index',
        ),
        migrations.RemoveConstraint(
            model_name='clueplacement',
            name='clue_placement_unique_row_col_direction',
        ),
        migrations.RemoveConstraint(
            model_name='clueplacement',
            name='clue_placement_unique_board_clue',
        ),
        migrations.AddField(
            model_name='placement',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='crossword.board'),
        ),
        migrations.AddField(
            model_name='placement',
            name='clue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.clue'),
        ),
        migrations.AddField(
            model_name='cell',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='crossword.placement'),
        ),
        migrations.RemoveField(
            model_name='cluecell',
            name='clue_placement',
        ),
        migrations.RemoveField(
            model_name='clueplacement',
            name='board',
        ),
        migrations.RemoveField(
            model_name='clueplacement',
            name='clue',
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(fields=('board', 'start_row', 'start_col', 'direction'), name='placement_unique_row_col_direction'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(fields=('board', 'clue'), name='placement_unique_board_clue'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['row_index', 'col_index'], name='cell_row_col_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('placement', 'row_index', 'col_index'), name='cell_unique_placement_row_col'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('placement', 'placement_index'), name='cell_unique_placement_placement_index'),
        ),
        migrations.DeleteModel(
            name='ClueCell',
        ),
        migrations.DeleteModel(
            name='CluePlacement',
        ),
    ]
