# Generated by Django 6.0.2 on 2026-06-15 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0027_cell_placement_remove_cluecell_cluecell_row_col_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='placement',
            name='placement_unique_board_clue',
        ),
        migrations.AddField(
            model_name='clue',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='crossword.board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placement',
            name='clue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='crossword.clue'),
        ),
    ]
