# Generated by Django 6.0.2 on 2026-06-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0028_remove_placement_placement_unique_board_clue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='categories',
        ),
    ]
