# Generated by Django 6.0.2 on 2026-07-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0029_remove_clue_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('puzzle', 'Puzzle'), ('design_note', 'Design Note'), ('exhibit', 'Exhibit')], max_length=32, unique=True)),
                ('current_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhibit_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='exhibits', to='crossword.category')),
            ],
            options={
                'ordering': ['exhibit_number'],
            },
        ),
    ]
