# Generated by Django 6.0.6 on 2026-10-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0030_contentsequence_exhibit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='board',
            name='board_symmetry',
        ),
        migrations.RemoveField(
            model_name='board',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='board',
            name='rows',
        ),
    ]
