# Generated by Django 6.0.2 on 2026-02-17 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(21)])),
                ('cols', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(21)])),
                ('categories', models.ManyToManyField(null=True, related_name='Boards', to='criss_cross.category')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer_raw', models.CharField(max_length=21)),
                ('answer_normalized', models.CharField(max_length=21)),
                ('answer_length', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(null=True, related_name='Clues', to='criss_cross.category')),
            ],
        ),
        migrations.CreateModel(
            name='CluePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_row', models.PositiveIntegerField()),
                ('start_col', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('A', 'Across'), ('D', 'Down')], max_length=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criss_cross.board')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criss_cross.clue')),
            ],
        ),
        migrations.CreateModel(
            name='ClueCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('col_index', models.PositiveIntegerField()),
                ('answer_index', models.PositiveIntegerField()),
                ('clue_placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criss_cross.clueplacement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.CheckConstraint(condition=models.Q(('cols', models.F('rows'))), name='board_symmetry'),
        ),
        migrations.AddConstraint(
            model_name='clueplacement',
            constraint=models.UniqueConstraint(fields=('board', 'start_row', 'start_col', 'direction'), name='clue_placement_unique_row_col_direction'),
        ),
        migrations.AddConstraint(
            model_name='clueplacement',
            constraint=models.UniqueConstraint(fields=('board', 'clue'), name='clue_placement_unique_board_clue'),
        ),
        migrations.AddConstraint(
            model_name='cluecell',
            constraint=models.UniqueConstraint(fields=('clue_placement', 'row_index', 'col_index'), name='clue_cell_unique_placement_row_col'),
        ),
        migrations.AddConstraint(
            model_name='cluecell',
            constraint=models.UniqueConstraint(fields=('clue_placement', 'answer_index'), name='clue_cell_unique_index_per_placement'),
        ),
    ]
