# Generated by Django 6.0.2 on 2026-02-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criss_cross', '0003_board_created_at_board_title_board_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='answer_normalized',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='answer_raw',
        ),
    ]
